### PR TITLE
fixing typos

### PR DESCRIPTION
**Pull request by jenlindner**

### CODE REVIEW

**Comment by jenlindner** [comment]
@little9 this now has the work we just looked at, populating the committee members structures without duplicating, etc.

**Comment by little9** [comment]
@jenlindner Do you think these test failures are real?

**Comment by jenlindner** [comment]
@little9 Yes. I just pushed a branch with a fix, making a pr now.

**Comment by little9** [comment]
@jenlindner I think we can close this because of the other committee member PR

**Pull request closed without merging**
