### PR TITLE
Updates links to submission PDFs

### PR DESCRIPTION
**Pull request by rotated8**
SCO has updated the PDFs with new names, which these new links point to.

### CODE REVIEW

**Comment by rotated8** [comment]
@mark-dce CI is erroring out when yarn tries to find Python 2. Do you have any suggestions?

**Comment by mark-dce** [comment]
@rotated8 I'm 98% sure this is related to CircleCI retiring it's legacy convenience images.   Other folks are seeing a very similar error (and I'm seeing the exact same error on trivial changes) - see for example https://discuss.circleci.com/t/started-11-1-2021-cant-find-python-executable-python-you-can-set-the-python-env-variable/41734

I tried running with the updated Samvera or in Chris's PR, but I think there are still some kinks there.  I've described them on my comments to his PR https://github.com/samvera-labs/samvera-circleci-orb/pull/52#issuecomment-997305962

**Review by mark-dce — APPROVED** [review]

**Comment by mark-dce** [comment]
In the interim to having a CircleCI fix, I ran the test suite on my local system where all tests passed. (Plus these changes really shouldn't be able to break anything.)

**Comment by mark-dce** [comment]
Merged, released, and deployed to production (https://etd.library.emory.edu).  
The screenshot below shows one of the updated links.

image

**Pull request merged**
