### PR TITLE
disable deprecation warnings in ci

### PR DESCRIPTION
**Pull request by jenlindner**
Because the slowness they seem to add seems to be interfering with our Travis builds.

### CODE REVIEW

**Comment by mark-dce** [comment]
Before we do this, could you:
 1) provide a comparison of timings of the average of three runs with deprecation warnings and three runs without
2) run the test suite with the [--profile](https://relishapp.com/rspec/rspec-core/docs/configuration/profile-examples) option and evaluate whether there are any particularly slow tests that are redundant or could be refactored to run more quickly

If we have that information in hand, I'd be much more comfortable having a discussion about whether to turn off deprecation warnings or not.

**Comment by mark-dce** [comment]
I'd also be willing to discuss devoting a 1-2 day spike to resolving deprecations if that was useful.

**Comment by no-reply** [comment]
I'd like to just cleanup the deprecations today.

**Comment by no-reply** [comment]
I started work on the deprecation cleanup at: https://github.com/curationexperts/laevigata/pull/1135

**Pull request closed without merging**
