### PR TITLE
bundle update

### LINKED ISSUE #860: bundle update
- [x] update ruby libraries

### PR DESCRIPTION
**Pull request by bess**
Closes #860

### CODE REVIEW

**Comment by bess** [comment]
@jenlindner We still need a bundle update, and it's still failing. Pinning pg and jasmine doesn't seem to have been enough. :(

**Comment by bess** [comment]
@jenlindner Any ideas on what could cause this?
```
Capybara::Webkit::JavaScriptError:
            {:line_number=>112417, :message=>"ReferenceError: Can't find variable: global", :source=>"http://127.0.0.1:37331/assets/application-bf582c70e6b5694e9c8ccfc5fe911e12a27fa1134439924233ecac993bdc1585.js"},{:line_number=>82113, :message=>"ReferenceError: Can't find variable: checklist_selector", :source=>"http://127.0.0.1:37331/assets/application-bf582c70e6b5694e9c8ccfc5fe911e12a27fa1134439924233ecac993bdc1585.js"}
```

**Comment by jenlindner** [comment]
@bess - No, I thought it was caused by Jasmine. I'll do some research.

**Comment by jenlindner** [comment]
@bess I found out what's causing this, it's a tinymce problem, a variable being referenced before it's been defined. Still trying to prevent it from happening though.

**Comment by bess** [comment]
@jenlindner That's great, thank you!

**Comment by jenlindner** [comment]
@bess 💚 💚 💚

**Pull request merged**
